# Generated by Django 4.0.4 on 2022-05-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userName', models.TextField()),
                ('userEmail', models.TextField()),
                ('userId', models.TextField(primary_key=True, serialize=False)),
                ('userPassword', models.TextField()),
                ('userSex', models.TextField()),
                ('userAge', models.TextField()),
                ('userImage', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPartner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userPartnerName', models.TextField(null=True)),
                ('userPartnerDate', models.IntegerField(null=True)),
                ('userPartnerImage', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preferenceEat', models.TextField(blank=True)),
                ('preferencePlay', models.TextField(blank=True)),
                ('preferenceDrink', models.TextField(blank=True)),
                ('preferenceSee', models.TextField(blank=True)),
                ('preferenceWalk', models.TextField(blank=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userinfo')),
            ],
        ),
    ]
