# Generated by Django 4.0.4 on 2022-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpartner',
            name='userPartnerDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='userPartnerImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='userPartnerName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
