# Generated by Django 4.0.4 on 2022-06-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_userpartner_userpartnerdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='preferencePlay',
            new_name='preferenceCafe',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferenceSee',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferenceWalk',
        ),
        migrations.DeleteModel(
            name='UserPartner',
        ),
    ]
