# Generated by Django 4.0.4 on 2022-06-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_preferenceplay_userpreference_preferencecafe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='preferenceCafe',
            new_name='userPreferenceCafe',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='preferenceDrink',
            new_name='userPreferenceDrink',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='preferenceEat',
            new_name='userPreferenceEat',
        ),
    ]
